/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.swig;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform;
import org.gradle.nativeplatform.toolchain.NativeToolChainRegistry;
import org.gradle.nativeplatform.toolchain.internal.plugins.StandardToolChainsPlugin;

import javax.inject.Inject;

/*private*/ abstract /*final*/ class SwigPlugin implements Plugin<Project> {
    @Inject
    public SwigPlugin() {}

    public void apply(Project project) {
        project.getPluginManager().apply(StandardToolChainsPlugin.class);
        project.getTasks().register("swig", SwigTask.class, task -> {
            task.getToolChain().set(project.getExtensions().getByType(NativeToolChainRegistry.class).getForPlatform(DefaultNativePlatform.host()));
            task.getTargetPlatform().set(DefaultNativePlatform.host());
        });
    }
}
